version: 0.0
os: linux
files:
  - source: /
    destination: /home/api/api_back
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/api
    pattern: "**"
    owner: root
    group: root

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BusiDiag?serverTimezone=UTC
    username: dev
    password: dev123!

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update